"""Internal web UI asset assembly package."""

from .assembler import (
    BOARD_WEB_APP_CONTRACT_TEXT,
    BOARD_WEB_APP_CSS,
    BOARD_WEB_APP_CSS_PATH,
    BOARD_WEB_APP_HTML,
    BOARD_WEB_APP_JS,
    BOARD_WEB_APP_JS_PATH,
    BOARD_WEB_APP_MODULE_MANIFEST,
    BOARD_WEB_APP_MODULES,
    MANAGER_STRUCTURE_HTML,
    MODULE_MAP_HTML,
    MODULE_MAP_INFRASTRUCTURE,
    TELEGRAM_AGENT_BEHAVIOR,
    TELEGRAM_AGENT_BEHAVIOR_HTML,
)

__all__ = [
    "BOARD_WEB_APP_CONTRACT_TEXT",
    "BOARD_WEB_APP_CSS",
    "BOARD_WEB_APP_CSS_PATH",
    "BOARD_WEB_APP_HTML",
    "BOARD_WEB_APP_JS",
    "BOARD_WEB_APP_JS_PATH",
    "BOARD_WEB_APP_MODULES",
    "BOARD_WEB_APP_MODULE_MANIFEST",
    "MODULE_MAP_HTML",
    "MANAGER_STRUCTURE_HTML",
    "MODULE_MAP_INFRASTRUCTURE",
    "TELEGRAM_AGENT_BEHAVIOR",
    "TELEGRAM_AGENT_BEHAVIOR_HTML",
]
