repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: ruff format --check
        language: python
        additional_dependencies: [ruff]
        types: [python]
      - id: ruff-check
        name: ruff check
        entry: ruff check
        language: python
        additional_dependencies: [ruff]
        types: [python]
