from __future__ import annotations

import sys
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from minimal_kanban.web_assets import BOARD_WEB_APP_HTML


class WebAssetsTests(unittest.TestCase):
    def test_board_brand_uses_autostop_name(self) -> None:
        self.assertIn("<title>AutoStop</title>", BOARD_WEB_APP_HTML)
        self.assertIn('<div class="brand__title">AUTOSTOP / ПУЛЬТ</div>', BOARD_WEB_APP_HTML)
        self.assertNotIn('<div class="brand__title">КАНБАН / ПУЛЬТ</div>', BOARD_WEB_APP_HTML)

    def test_board_settings_keep_slider_but_remove_wheel_zoom_binding(self) -> None:
        self.assertIn('id="boardScaleInput"', BOARD_WEB_APP_HTML)
        self.assertIn('class="scale-track"', BOARD_WEB_APP_HTML)
        self.assertNotIn("addEventListener('wheel'", BOARD_WEB_APP_HTML)
        self.assertNotIn("function handleBoardWheel", BOARD_WEB_APP_HTML)
        self.assertIn("grid-template-rows: auto auto minmax(0, 1fr);", BOARD_WEB_APP_HTML)
        self.assertIn("--board-gutter-left: 0px;", BOARD_WEB_APP_HTML)
        self.assertIn("--board-gutter-top: 0px;", BOARD_WEB_APP_HTML)
        self.assertIn(".status-shell .message {", BOARD_WEB_APP_HTML)
        self.assertIn("width: max-content;", BOARD_WEB_APP_HTML)

    def test_card_tag_editor_uses_compact_tag_controls(self) -> None:
        self.assertIn(".tags-panel {", BOARD_WEB_APP_HTML)
        self.assertIn(".tags-panel__head {", BOARD_WEB_APP_HTML)
        self.assertIn(".tag-limit {", BOARD_WEB_APP_HTML)
        self.assertIn(".tag-list .tag {", BOARD_WEB_APP_HTML)
        self.assertIn('class="tag-suggestions" id="tagSuggestions"', BOARD_WEB_APP_HTML)
        self.assertIn('class="tag-entry"', BOARD_WEB_APP_HTML)
        self.assertIn('class="field field--tags"', BOARD_WEB_APP_HTML)
        self.assertIn('id="tagMeta"', BOARD_WEB_APP_HTML)
        self.assertIn("МЕТОК НЕТ", BOARD_WEB_APP_HTML)
        self.assertIn(" + ' ×</button>'", BOARD_WEB_APP_HTML)
        self.assertIn(".column > * {", BOARD_WEB_APP_HTML)

    def test_modal_uses_themed_scrollbars(self) -> None:
        self.assertIn("--scroll-track:", BOARD_WEB_APP_HTML)
        self.assertIn("scrollbar-color: var(--scroll-thumb) var(--scroll-track);", BOARD_WEB_APP_HTML)
        self.assertIn("*::-webkit-scrollbar-thumb {", BOARD_WEB_APP_HTML)

    def test_columns_expose_hidden_delete_button_with_guarded_flow(self) -> None:
        self.assertIn(".column__delete {", BOARD_WEB_APP_HTML)
        self.assertIn(".column:hover .column__delete,", BOARD_WEB_APP_HTML)
        self.assertIn("data-delete-column", BOARD_WEB_APP_HTML)
        self.assertIn("async function deleteColumnFromButton(button)", BOARD_WEB_APP_HTML)
        self.assertIn("Удалить пустой столбец", BOARD_WEB_APP_HTML)
        self.assertIn("window.confirm('Удалить пустой столбец", BOARD_WEB_APP_HTML)
        self.assertIn("'/api/delete_column'", BOARD_WEB_APP_HTML)
        self.assertIn("await deleteColumnFromButton(deleteColumnButton);", BOARD_WEB_APP_HTML)

    def test_columns_expose_rename_flow(self) -> None:
        self.assertIn("data-rename-column", BOARD_WEB_APP_HTML)
        self.assertIn("async function renameColumnFromButton(button)", BOARD_WEB_APP_HTML)
        self.assertIn("'/api/rename_column'", BOARD_WEB_APP_HTML)
        self.assertIn("window.prompt(", BOARD_WEB_APP_HTML)
        self.assertIn("await renameColumnFromButton(renameColumnButton);", BOARD_WEB_APP_HTML)

    def test_board_snapshot_polling_is_throttled_and_visibility_aware(self) -> None:
        self.assertIn("refreshInFlight: null", BOARD_WEB_APP_HTML)
        self.assertIn("const SNAPSHOT_POLL_INTERVAL_MS = 5000;", BOARD_WEB_APP_HTML)
        self.assertIn("const SNAPSHOT_POLL_HIDDEN_INTERVAL_MS = 30000;", BOARD_WEB_APP_HTML)
        self.assertIn("function snapshotPollIntervalMs()", BOARD_WEB_APP_HTML)
        self.assertIn("function scheduleNextSnapshotPoll()", BOARD_WEB_APP_HTML)
        self.assertIn("function handleSnapshotVisibilityChange()", BOARD_WEB_APP_HTML)
        self.assertIn("if (!document.hidden) refreshSnapshot(false);", BOARD_WEB_APP_HTML)
        self.assertIn("document.addEventListener('visibilitychange', handleSnapshotVisibilityChange);", BOARD_WEB_APP_HTML)
        self.assertIn("state.pollHandle = window.setTimeout(async () => {", BOARD_WEB_APP_HTML)
        self.assertIn("await refreshSnapshot(false);", BOARD_WEB_APP_HTML)
        self.assertIn("scheduleNextSnapshotPoll();", BOARD_WEB_APP_HTML)

    def test_archive_modal_uses_last_30_compact_rows(self) -> None:
        self.assertIn("АРХИВ / ПОСЛЕДНИЕ 30", BOARD_WEB_APP_HTML)
        self.assertIn("/api/get_board_snapshot?archive_limit=30&compact=1", BOARD_WEB_APP_HTML)
        self.assertIn(".archive-row--compact {", BOARD_WEB_APP_HTML)
        self.assertIn(".archive-row__summary {", BOARD_WEB_APP_HTML)
        self.assertIn("renderArchive = function() {", BOARD_WEB_APP_HTML)
        self.assertIn("compactDescription.length > 180", BOARD_WEB_APP_HTML)
        self.assertIn("archive-row archive-row--compact", BOARD_WEB_APP_HTML)
        self.assertIn("await restoreCard(target.dataset.restoreCard);", BOARD_WEB_APP_HTML)

    def test_sticky_dock_uses_single_icon_button_without_dropdown(self) -> None:
        self.assertIn('class="sticky-dock__button" id="stickyDockButton"', BOARD_WEB_APP_HTML)
        self.assertIn('aria-label="Новый стикер"', BOARD_WEB_APP_HTML)
        self.assertIn('title="Новый стикер"', BOARD_WEB_APP_HTML)
        self.assertIn(".sticky-dock__button svg {", BOARD_WEB_APP_HTML)
        self.assertNotIn("stickyDockMenu", BOARD_WEB_APP_HTML)
        self.assertNotIn("stickyCreateButton", BOARD_WEB_APP_HTML)
        self.assertNotIn("toggleStickyMenu", BOARD_WEB_APP_HTML)
        self.assertNotIn("closeStickyMenu", BOARD_WEB_APP_HTML)
        self.assertIn(".sticky__text {", BOARD_WEB_APP_HTML)
        self.assertIn("font-size: calc(15px * var(--board-scale));", BOARD_WEB_APP_HTML)
        self.assertIn("color: rgba(104, 42, 39, 0.94);", BOARD_WEB_APP_HTML)
        self.assertIn("async function handleAuxiliaryBoardClick(target, event)", BOARD_WEB_APP_HTML)
        self.assertIn("function handleStickyModalOverlayClick(event)", BOARD_WEB_APP_HTML)
        self.assertIn("function applyStickySnapshot(stickies)", BOARD_WEB_APP_HTML)
        self.assertIn("if (target === els.stickyDockButton || target.closest('#stickyDockButton')) {", BOARD_WEB_APP_HTML)
        self.assertIn("if (await handleAuxiliaryBoardClick(target, event)) return;", BOARD_WEB_APP_HTML)
        self.assertIn("els.stickyModal.addEventListener('click', handleStickyModalOverlayClick);", BOARD_WEB_APP_HTML)
        self.assertIn("if (applyStickySnapshot(data?.stickies || [])) {", BOARD_WEB_APP_HTML)

    def test_card_description_textarea_allows_extended_text(self) -> None:
        self.assertIn('id="cardDescription" maxlength="20000"', BOARD_WEB_APP_HTML)
        self.assertIn(".field--description textarea {", BOARD_WEB_APP_HTML)
        self.assertIn("min-height: 168px;", BOARD_WEB_APP_HTML)
        self.assertIn("height: 168px;", BOARD_WEB_APP_HTML)
        self.assertIn("function syncCardDescriptionHeight()", BOARD_WEB_APP_HTML)
        self.assertIn("els.cardDescription.addEventListener('input', syncCardDescriptionHeight);", BOARD_WEB_APP_HTML)
        self.assertIn("requestAnimationFrame(() => syncCardDescriptionHeight());", BOARD_WEB_APP_HTML)

    def test_card_form_semantics_distinguish_make_model_and_short_essence(self) -> None:
        self.assertIn("const CARD_VEHICLE_FIELD_LABEL = 'Марка / модель';", BOARD_WEB_APP_HTML)
        self.assertIn("const CARD_TITLE_FIELD_LABEL = 'Краткая суть';", BOARD_WEB_APP_HTML)
        self.assertIn("const CARD_TITLE_REQUIRED_MESSAGE = 'УКАЖИ КРАТКУЮ СУТЬ КАРТОЧКИ.';", BOARD_WEB_APP_HTML)
        self.assertIn("function configureCardFieldSemantics()", BOARD_WEB_APP_HTML)
        self.assertIn("vehicleLabel.textContent = 'МАРКА / МОДЕЛЬ';", BOARD_WEB_APP_HTML)
        self.assertIn("els.cardVehicle.placeholder = 'Nissan Teana J32';", BOARD_WEB_APP_HTML)
        self.assertIn("titleLabel.textContent = 'КРАТКАЯ СУТЬ';", BOARD_WEB_APP_HTML)
        self.assertIn("els.cardTitle.placeholder = 'Краткая суть проблемы, задачи или результата';", BOARD_WEB_APP_HTML)
        self.assertIn("parts.push(CARD_VEHICLE_FIELD_LABEL + ': ' + vehicle);", BOARD_WEB_APP_HTML)
        self.assertIn("parts.push(CARD_TITLE_FIELD_LABEL + ': ' + title);", BOARD_WEB_APP_HTML)
        self.assertIn("configureCardFieldSemantics();", BOARD_WEB_APP_HTML)

    def test_board_cards_show_eight_lines_of_description_preview(self) -> None:
        self.assertIn(".card__desc {", BOARD_WEB_APP_HTML)
        self.assertIn("-webkit-line-clamp: 8;", BOARD_WEB_APP_HTML)

    def test_card_modal_includes_centered_work_zone_and_separate_vehicle_panel(self) -> None:
        self.assertIn('class="dialog dialog--card"', BOARD_WEB_APP_HTML)
        self.assertIn(".dialog--card {", BOARD_WEB_APP_HTML)
        self.assertIn('class="dialog__head dialog__head--card"', BOARD_WEB_APP_HTML)
        self.assertIn(".dialog__title--card {", BOARD_WEB_APP_HTML)
        self.assertIn("text-overflow: ellipsis;", BOARD_WEB_APP_HTML)
        self.assertIn("function limitCardModalHeading(value, maxLength = 92)", BOARD_WEB_APP_HTML)
        self.assertIn("grid-template-columns: minmax(640px, 760px) minmax(286px, 338px);", BOARD_WEB_APP_HTML)
        self.assertIn('class="subpanel vehicle-panel"', BOARD_WEB_APP_HTML)
        self.assertIn("z-index: 2;", BOARD_WEB_APP_HTML)
        self.assertIn("isolation: isolate;", BOARD_WEB_APP_HTML)
        self.assertIn(".vehicle-panel::before {", BOARD_WEB_APP_HTML)
        self.assertIn('id="vehiclePanelSummary"', BOARD_WEB_APP_HTML)
        self.assertNotIn('id="vehiclePanelFlags"', BOARD_WEB_APP_HTML)
        self.assertIn('id="vehicleProfileFields"', BOARD_WEB_APP_HTML)
        self.assertIn(".overview-main__meta {", BOARD_WEB_APP_HTML)
        self.assertIn("function applyCardModalState(card)", BOARD_WEB_APP_HTML)
        self.assertIn("function resetCardModalState()", BOARD_WEB_APP_HTML)
        self.assertIn("async function persistCardPayload(payload)", BOARD_WEB_APP_HTML)
        self.assertIn("async function openCardWorkspace(cardId, { closeModalEl = null, openRepairOrder = false } = {})", BOARD_WEB_APP_HTML)
        self.assertIn("function openNewCardInColumn(columnId)", BOARD_WEB_APP_HTML)
        self.assertIn("function openDefaultNewCard()", BOARD_WEB_APP_HTML)
        self.assertIn("async function archiveActiveCard()", BOARD_WEB_APP_HTML)
        self.assertIn("async function restoreActiveCard()", BOARD_WEB_APP_HTML)
        self.assertIn("async function handleCardWorkspaceClick(target)", BOARD_WEB_APP_HTML)
        self.assertIn("applyCardModalState(card);", BOARD_WEB_APP_HTML)
        self.assertIn("resetCardModalState();", BOARD_WEB_APP_HTML)
        self.assertIn("await persistCardPayload(payload);", BOARD_WEB_APP_HTML)
        self.assertIn("await openCardWorkspace(cardId);", BOARD_WEB_APP_HTML)
        self.assertIn("if (target.dataset.createIn) openNewCardInColumn(target.dataset.createIn);", BOARD_WEB_APP_HTML)
        self.assertIn("if (await handleCardWorkspaceClick(target)) return;", BOARD_WEB_APP_HTML)
        self.assertIn("els.cardButton.addEventListener('click', openDefaultNewCard);", BOARD_WEB_APP_HTML)
        self.assertIn("els.archiveAction.addEventListener('click', archiveActiveCard);", BOARD_WEB_APP_HTML)
        self.assertIn("els.restoreAction.addEventListener('click', restoreActiveCard);", BOARD_WEB_APP_HTML)

    def test_vehicle_panel_exposes_only_minimal_profile_fields(self) -> None:
        self.assertIn('id="vehicleAutofillButton"', BOARD_WEB_APP_HTML)
        self.assertIn("function configureVehicleAutofillUi()", BOARD_WEB_APP_HTML)
        self.assertIn("function buildVehicleAutofillRawText()", BOARD_WEB_APP_HTML)
        self.assertIn("await copyVehicleFieldValue(target.dataset.copyVehicleField);", BOARD_WEB_APP_HTML)
        self.assertNotIn("payload.image_base64", BOARD_WEB_APP_HTML)
        self.assertNotIn("vehicleAutofillImage.files?.[0]", BOARD_WEB_APP_HTML)
        self.assertNotIn('id="vehicleAutofillText"', BOARD_WEB_APP_HTML)
        self.assertNotIn('id="vehicleAutofillImage"', BOARD_WEB_APP_HTML)
        self.assertNotIn('id="vehicleAutofillStatus"', BOARD_WEB_APP_HTML)
        self.assertNotIn("Доп. данные:", BOARD_WEB_APP_HTML)
        self.assertNotIn("АНАЛИЗ ПОЛЕЙ КАРТОЧКИ", BOARD_WEB_APP_HTML)
        self.assertIn("const VEHICLE_FIELD_GROUPS = [", BOARD_WEB_APP_HTML)
        self.assertIn("make_display", BOARD_WEB_APP_HTML)
        self.assertIn("model_display", BOARD_WEB_APP_HTML)
        self.assertIn("production_year", BOARD_WEB_APP_HTML)
        self.assertIn("mileage", BOARD_WEB_APP_HTML)
        self.assertIn("customer_phone", BOARD_WEB_APP_HTML)
        self.assertIn("customer_name", BOARD_WEB_APP_HTML)
        self.assertIn("vin", BOARD_WEB_APP_HTML)
        self.assertIn("engine_model", BOARD_WEB_APP_HTML)
        self.assertIn("gearbox_model", BOARD_WEB_APP_HTML)
        self.assertIn("drivetrain", BOARD_WEB_APP_HTML)
        self.assertNotIn("oem_notes', label: 'Короткая заметка'", BOARD_WEB_APP_HTML)
        self.assertNotIn("{ name: 'engine_code'", BOARD_WEB_APP_HTML)
        self.assertNotIn("{ name: 'generation_or_platform'", BOARD_WEB_APP_HTML)
        self.assertIn("function autofillVehicleProfile()", BOARD_WEB_APP_HTML)
        self.assertIn("vehicle_profile: vehicleProfile,", BOARD_WEB_APP_HTML)

    def test_vehicle_panel_hides_empty_summary_and_first_group_title(self) -> None:
        self.assertIn("VEHICLE_FIELD_GROUPS[0].title = '';", BOARD_WEB_APP_HTML)
        self.assertIn("Пробег", BOARD_WEB_APP_HTML)
        self.assertIn("Телефон клиента", BOARD_WEB_APP_HTML)
        self.assertIn("ФИО клиента", BOARD_WEB_APP_HTML)
        self.assertIn("(group.title ? '<div class=\"vehicle-group__title\">' + escapeHtml(group.title) + '</div>' : '')", BOARD_WEB_APP_HTML)
        self.assertIn("if (profile.vin) summaryLines.push('VIN: ' + profile.vin);", BOARD_WEB_APP_HTML)
        self.assertIn("if (profile.mileage) summaryLines.push('Пробег: ' + profile.mileage);", BOARD_WEB_APP_HTML)
        self.assertNotIn("const display = vehicleDisplayFromProfile(profile);", BOARD_WEB_APP_HTML)
        self.assertIn("els.vehiclePanelSummary.style.display = summaryLines.length ? '' : 'none';", BOARD_WEB_APP_HTML)

    def test_vehicle_panel_collapses_cleanly_on_narrow_screens(self) -> None:
        self.assertIn("@media (max-width: 900px) {", BOARD_WEB_APP_HTML)
        self.assertIn(".vehicle-group__grid { grid-template-columns: 1fr; }", BOARD_WEB_APP_HTML)
        self.assertIn(".vehicle-panel__fields { max-height: none; }", BOARD_WEB_APP_HTML)
        self.assertIn(".vehicle-panel::before { display: none; }", BOARD_WEB_APP_HTML)
        self.assertIn(".dialog--card { width: min(1120px, 100%); }", BOARD_WEB_APP_HTML)

    def test_vehicle_panel_uses_larger_readable_typography(self) -> None:
        self.assertIn(".vehicle-panel__summary {", BOARD_WEB_APP_HTML)
        self.assertIn("font-size: 11px;", BOARD_WEB_APP_HTML)
        self.assertIn(".vehicle-group__title {", BOARD_WEB_APP_HTML)
        self.assertIn(".vehicle-field__label label,", BOARD_WEB_APP_HTML)
        self.assertIn(".vehicle-copy {", BOARD_WEB_APP_HTML)

    def test_cards_use_stepwise_deadline_heat_variables(self) -> None:
        self.assertIn("--deadline-heat-border:", BOARD_WEB_APP_HTML)
        self.assertIn("--deadline-heat-ring:", BOARD_WEB_APP_HTML)
        self.assertIn("--deadline-heat-glow:", BOARD_WEB_APP_HTML)
        self.assertIn("data-deadline-bucket", BOARD_WEB_APP_HTML)
        self.assertIn("data-deadline-step", BOARD_WEB_APP_HTML)
        self.assertIn("cards.map(renderBoardCardHtml).join('')", BOARD_WEB_APP_HTML)

    def test_cards_stack_vehicle_above_short_essence(self) -> None:
        self.assertIn(".card__heading {", BOARD_WEB_APP_HTML)
        self.assertIn("display: grid;", BOARD_WEB_APP_HTML)
        self.assertIn("font-size: calc(15px * var(--board-scale));", BOARD_WEB_APP_HTML)
        self.assertIn("font-size: calc(14px * var(--board-scale));", BOARD_WEB_APP_HTML)
        self.assertIn("color: #373227;", BOARD_WEB_APP_HTML)
        self.assertIn("color: #454034;", BOARD_WEB_APP_HTML)
        self.assertIn("function buildCardHeadingHtml(card)", BOARD_WEB_APP_HTML)
        self.assertIn("return '<div class=\"card__heading\"><div class=\"card__vehicle\">' + escapeHtml(vehicle) + '</div><div class=\"card__title\">' + escapeHtml(title) + '</div></div>';", BOARD_WEB_APP_HTML)
        self.assertIn("function renderBoardCardHtml(card)", BOARD_WEB_APP_HTML)
        self.assertIn("cards.map(renderBoardCardHtml).join('')", BOARD_WEB_APP_HTML)

    def test_card_timer_panel_uses_compact_number_fields(self) -> None:
        self.assertIn('<div class="panel-title">ОБРАТНЫЙ ОТСЧЁТ</div>', BOARD_WEB_APP_HTML)
        self.assertIn(".signal-grid--timer {", BOARD_WEB_APP_HTML)
        self.assertIn(".signal-grid--timer > .signal-cell:not(.signal-cell--timer) {", BOARD_WEB_APP_HTML)
        self.assertIn(".signal-input {", BOARD_WEB_APP_HTML)
        self.assertIn(".signal-input__field {", BOARD_WEB_APP_HTML)
        self.assertIn(".signal-input__unit {", BOARD_WEB_APP_HTML)
        self.assertIn('class="signal-grid signal-grid--timer"', BOARD_WEB_APP_HTML)
        self.assertIn('class="signal-cell signal-cell--timer"', BOARD_WEB_APP_HTML)
        self.assertIn('class="signal-input__field" id="signalDaysStyled"', BOARD_WEB_APP_HTML)
        self.assertIn('class="signal-input__field" id="signalHoursStyled"', BOARD_WEB_APP_HTML)
        self.assertIn('inputmode="numeric"', BOARD_WEB_APP_HTML)
        self.assertIn("document.getElementById('signalDaysStyled') || document.getElementById('signalDays')", BOARD_WEB_APP_HTML)
        self.assertIn("document.getElementById('signalHoursStyled') || document.getElementById('signalHours')", BOARD_WEB_APP_HTML)

    def test_card_preview_uses_readable_russian_meta_labels(self) -> None:
        self.assertIn("БЕЗ МЕТОК", BOARD_WEB_APP_HTML)
        self.assertIn("Описание не указано", BOARD_WEB_APP_HTML)
        self.assertIn("СИГН", BOARD_WEB_APP_HTML)
        self.assertIn("ФАЙЛЫ ", BOARD_WEB_APP_HTML)
        self.assertIn("ЖУРНАЛ ", BOARD_WEB_APP_HTML)

    def test_unread_cards_expose_corner_badge_and_hover_seen_flow(self) -> None:
        self.assertEqual(BOARD_WEB_APP_HTML.count("function cardHtml(card)"), 1)
        self.assertEqual(BOARD_WEB_APP_HTML.count("function renderCardHtml(card)"), 1)
        self.assertIn(".card__unread-badge {", BOARD_WEB_APP_HTML)
        self.assertIn("data-unread=\"' + (card.is_unread ? 'true' : 'false') + '\"", BOARD_WEB_APP_HTML)
        self.assertIn("title=\"Не прочитано\"", BOARD_WEB_APP_HTML)
        self.assertIn("const CARD_UNREAD_HOVER_DELAY_MS = 260;", BOARD_WEB_APP_HTML)
        self.assertIn("await api('/api/mark_card_seen'", BOARD_WEB_APP_HTML)
        self.assertIn("function handleCardSeenPointerOver(event)", BOARD_WEB_APP_HTML)
        self.assertIn("scheduleCardSeen(card.dataset.cardId);", BOARD_WEB_APP_HTML)
        self.assertIn("function handleCardSeenPointerOut(event)", BOARD_WEB_APP_HTML)
        self.assertIn("document.addEventListener('pointerover', handleCardSeenPointerOver);", BOARD_WEB_APP_HTML)
        self.assertIn("document.addEventListener('pointerout', handleCardSeenPointerOut);", BOARD_WEB_APP_HTML)

    def test_updated_cards_expose_yellow_badge_and_hover_seen_flow(self) -> None:
        self.assertIn(".card__updated-badge {", BOARD_WEB_APP_HTML)
        self.assertIn("data-updated-unseen=\"' + (card.has_unseen_update ? 'true' : 'false') + '\"", BOARD_WEB_APP_HTML)
        self.assertIn("title=\"Обновлено\"", BOARD_WEB_APP_HTML)
        self.assertIn("if (currentCard && !currentCard.is_unread && !currentCard.has_unseen_update) return;", BOARD_WEB_APP_HTML)
        self.assertIn("if (!currentCard || (!currentCard.is_unread && !currentCard.has_unseen_update)) return;", BOARD_WEB_APP_HTML)
        self.assertIn("const hasUpdatedMarker = card.dataset.updatedUnseen === 'true';", BOARD_WEB_APP_HTML)

    def test_board_drag_drop_supports_reordering_inside_column(self) -> None:
        self.assertIn(".card.is-drop-before::before {", BOARD_WEB_APP_HTML)
        self.assertIn("function resolveDropBeforeCardId(column, clientY, draggedCardId)", BOARD_WEB_APP_HTML)
        self.assertIn("function handleBoardCardDragStart(event)", BOARD_WEB_APP_HTML)
        self.assertIn("function handleBoardCardDragOver(event)", BOARD_WEB_APP_HTML)
        self.assertIn("function handleBoardCardDragLeave(event)", BOARD_WEB_APP_HTML)
        self.assertIn("async function handleBoardCardDrop(event)", BOARD_WEB_APP_HTML)
        self.assertIn("state.boardDropBeforeCardId = beforeCardId || '';", BOARD_WEB_APP_HTML)
        self.assertIn("before_card_id: beforeCardId || undefined,", BOARD_WEB_APP_HTML)
        self.assertIn("await moveCard(cardId, columnId, beforeCardId);", BOARD_WEB_APP_HTML)
        self.assertIn("document.addEventListener('dragstart', handleBoardCardDragStart);", BOARD_WEB_APP_HTML)
        self.assertIn("document.addEventListener('dragover', handleBoardCardDragOver);", BOARD_WEB_APP_HTML)
        self.assertIn("document.addEventListener('dragleave', handleBoardCardDragLeave);", BOARD_WEB_APP_HTML)
        self.assertIn("document.addEventListener('drop', handleBoardCardDrop);", BOARD_WEB_APP_HTML)
        self.assertIn("left.position ?? 0", BOARD_WEB_APP_HTML)

    def test_card_files_panel_uses_dropzone_and_clipboard_upload_flow(self) -> None:
        self.assertIn('class="file-dropzone" id="fileDropzone"', BOARD_WEB_APP_HTML)
        self.assertIn('contenteditable="plaintext-only"', BOARD_WEB_APP_HTML)
        self.assertIn('id="fileDropMeta"', BOARD_WEB_APP_HTML)
        self.assertIn('accept=".txt,.pdf,.doc,.docx,.xls,.xlsx', BOARD_WEB_APP_HTML)
        self.assertIn("function syncFileDropzone(card = state.activeCard)", BOARD_WEB_APP_HTML)
        self.assertIn("function requireSavedCardForFiles({ syncDropzone = false } = {})", BOARD_WEB_APP_HTML)
        self.assertIn("async function refreshActiveCardFiles()", BOARD_WEB_APP_HTML)
        self.assertIn("async function removeActiveCardAttachment(attachmentId)", BOARD_WEB_APP_HTML)
        self.assertIn("function collectClipboardAttachmentFiles(event)", BOARD_WEB_APP_HTML)
        self.assertIn("new File([text], clipboardTextAttachmentName()", BOARD_WEB_APP_HTML)
        self.assertIn("async function uploadProvidedFiles(files)", BOARD_WEB_APP_HTML)
        self.assertIn("function openFilePickerFromDropzone()", BOARD_WEB_APP_HTML)
        self.assertIn("function handleFileDropzoneKeydown(event)", BOARD_WEB_APP_HTML)
        self.assertIn("function handleFileDropzoneDragEnter(event)", BOARD_WEB_APP_HTML)
        self.assertIn("async function handleFileDropzoneDrop(event)", BOARD_WEB_APP_HTML)
        self.assertIn("async function handleFileDropzonePaste(event)", BOARD_WEB_APP_HTML)
        self.assertIn("if (!requireSavedCardForFiles({ syncDropzone: true })) return;", BOARD_WEB_APP_HTML)
        self.assertIn("await refreshActiveCardFiles();", BOARD_WEB_APP_HTML)
        self.assertIn("await removeActiveCardAttachment(target.dataset.removeFile);", BOARD_WEB_APP_HTML)
        self.assertIn("els.fileInput.addEventListener('change', () => uploadProvidedFiles(els.fileInput.files));", BOARD_WEB_APP_HTML)
        self.assertIn("els.fileDropzone.addEventListener('click', openFilePickerFromDropzone);", BOARD_WEB_APP_HTML)
        self.assertIn("els.fileDropzone.addEventListener('drop', handleFileDropzoneDrop);", BOARD_WEB_APP_HTML)
        self.assertIn("els.fileDropzone.addEventListener('paste', handleFileDropzonePaste);", BOARD_WEB_APP_HTML)
        self.assertIn("const attachmentLink = target.closest('a[href*=\"/api/attachment\"]');", BOARD_WEB_APP_HTML)
        self.assertIn("if (target.dataset.removeFile && state.editingId) {", BOARD_WEB_APP_HTML)

    def test_operator_ui_exposes_login_profile_and_admin_routes(self) -> None:
        self.assertNotIn("const ACTOR_STORAGE_KEY = 'kanban-actor';", BOARD_WEB_APP_HTML)
        self.assertIn("const OPERATOR_SESSION_STORAGE_KEY = 'kanban-operator-session';", BOARD_WEB_APP_HTML)
        self.assertEqual(BOARD_WEB_APP_HTML.count("function ensureActor()"), 1)
        self.assertNotIn("localStorage.setItem(ACTOR_STORAGE_KEY", BOARD_WEB_APP_HTML)
        self.assertNotIn("localStorage.removeItem(ACTOR_STORAGE_KEY", BOARD_WEB_APP_HTML)
        self.assertIn("'X-Operator-Session'", BOARD_WEB_APP_HTML)
        self.assertIn('id="operatorProfileModal"', BOARD_WEB_APP_HTML)
        self.assertIn('id="operatorSecurityNotice"', BOARD_WEB_APP_HTML)
        self.assertIn('id="operatorAdminModal"', BOARD_WEB_APP_HTML)
        self.assertIn('id="identityPassword"', BOARD_WEB_APP_HTML)
        self.assertIn('id="adminUserLogin"', BOARD_WEB_APP_HTML)
        self.assertIn('id="adminUserPassword"', BOARD_WEB_APP_HTML)
        self.assertNotIn('id="adminUserRole"', BOARD_WEB_APP_HTML)
        self.assertNotIn("role: els.adminUserRole.value", BOARD_WEB_APP_HTML)
        self.assertNotIn("els.adminUserRole.value = 'operator';", BOARD_WEB_APP_HTML)
        self.assertIn("Администратор создает пользователя или обновляет ему пароль.", BOARD_WEB_APP_HTML)
        self.assertIn('input[type="text"], input[type="password"], textarea, select, input[type="number"]', BOARD_WEB_APP_HTML)
        self.assertIn("color-scheme: dark;", BOARD_WEB_APP_HTML)
        self.assertIn(".field--compact input[type=\"password\"]", BOARD_WEB_APP_HTML)
        self.assertIn("input:-webkit-autofill", BOARD_WEB_APP_HTML)
        self.assertIn("async function loginOperator()", BOARD_WEB_APP_HTML)
        self.assertIn("function handleIdentityInputKeydown(event)", BOARD_WEB_APP_HTML)
        self.assertIn("function handleIdentityPasswordKeydown(event)", BOARD_WEB_APP_HTML)
        self.assertIn("async function loadOperatorProfile(openModal = false)", BOARD_WEB_APP_HTML)
        self.assertIn("async function openOperatorWorkspace()", BOARD_WEB_APP_HTML)
        self.assertIn("async function openOperatorAdminModal()", BOARD_WEB_APP_HTML)
        self.assertIn("async function saveOperatorUser()", BOARD_WEB_APP_HTML)
        self.assertIn("async function deleteOperatorUser(username)", BOARD_WEB_APP_HTML)
        self.assertIn("async function openOperatorUserReport(username)", BOARD_WEB_APP_HTML)
        self.assertIn("function handleAdminUsersListClick(event)", BOARD_WEB_APP_HTML)
        self.assertIn("data?.security?.warning || ''", BOARD_WEB_APP_HTML)
        self.assertIn("els.operatorSecurityNotice.classList.toggle('hidden', !securityWarning);", BOARD_WEB_APP_HTML)
        self.assertIn("els.operatorButton.addEventListener('click', openOperatorWorkspace);", BOARD_WEB_APP_HTML)
        self.assertIn("els.identityInput.addEventListener('keydown', handleIdentityInputKeydown);", BOARD_WEB_APP_HTML)
        self.assertIn("els.adminUsersList.addEventListener('click', handleAdminUsersListClick);", BOARD_WEB_APP_HTML)
        self.assertIn("'/api/login_operator'", BOARD_WEB_APP_HTML)
        self.assertIn("'/api/get_operator_profile'", BOARD_WEB_APP_HTML)
        self.assertIn("'/api/list_operator_users'", BOARD_WEB_APP_HTML)
        self.assertIn("'/api/get_operator_user_report?username='", BOARD_WEB_APP_HTML)
        self.assertIn("data-open-operator-report", BOARD_WEB_APP_HTML)
        self.assertIn("СТАТИСТИКА: 15 ДНЕЙ", BOARD_WEB_APP_HTML)
        self.assertIn("bootstrapOperatorSession();", BOARD_WEB_APP_HTML)

    def test_tag_editor_exposes_minimal_color_picker(self) -> None:
        self.assertIn('class="tag-color-picker" id="tagColorPicker"', BOARD_WEB_APP_HTML)
        self.assertIn(".tag-color-option {", BOARD_WEB_APP_HTML)
        self.assertIn("data-tag-color-choice", BOARD_WEB_APP_HTML)
        self.assertIn("draftTagColor: 'green'", BOARD_WEB_APP_HTML)
        self.assertIn("normalizeTagColor(", BOARD_WEB_APP_HTML)
        self.assertIn("function handleTagInputKeydown(event)", BOARD_WEB_APP_HTML)
        self.assertIn("els.tagInput.addEventListener('keydown', handleTagInputKeydown);", BOARD_WEB_APP_HTML)

    def test_tag_editor_limits_cards_to_three_tags(self) -> None:
        self.assertIn("const CARD_TAG_LIMIT = 3;", BOARD_WEB_APP_HTML)
        self.assertIn("slice(0, CARD_TAG_LIMIT)", BOARD_WEB_APP_HTML)
        self.assertIn("НА КАРТОЧКЕ МОЖЕТ БЫТЬ НЕ БОЛЕЕ 3 МЕТОК.", BOARD_WEB_APP_HTML)
        self.assertIn("els.tagMeta.textContent = state.draftTags.length + ' / ' + CARD_TAG_LIMIT;", BOARD_WEB_APP_HTML)
        self.assertIn("els.tagInput.disabled = atLimit;", BOARD_WEB_APP_HTML)
        self.assertIn("els.tagAddButton.disabled = atLimit;", BOARD_WEB_APP_HTML)
        self.assertIn("const disabledClass = disabled ? ' is-disabled' : '';", BOARD_WEB_APP_HTML)

    def test_green_tags_use_high_contrast_palette(self) -> None:
        self.assertIn('border-color: rgba(67, 126, 79, 0.82);', BOARD_WEB_APP_HTML)
        self.assertIn('background: rgba(111, 173, 116, 0.52);', BOARD_WEB_APP_HTML)
        self.assertIn('color: #1d1a14;', BOARD_WEB_APP_HTML)
        self.assertIn('.tag-color-option[data-tag-color="green"] { color: #3f8b52; }', BOARD_WEB_APP_HTML)
        self.assertIn('border-color: rgba(67, 126, 79, 0.62);', BOARD_WEB_APP_HTML)
        self.assertIn('background: rgba(111, 173, 116, 0.22);', BOARD_WEB_APP_HTML)

    def test_repair_order_modal_exposes_minimal_form_and_print_flow(self) -> None:
        self.assertIn('id="repairOrderButton" data-open-repair-order-modal="true"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrderModal"', BOARD_WEB_APP_HTML)
        self.assertIn("#repairOrderModal {", BOARD_WEB_APP_HTML)
        self.assertIn("z-index: 14;", BOARD_WEB_APP_HTML)
        self.assertIn('width: min(1380px, calc(100% - 18px));', BOARD_WEB_APP_HTML)
        self.assertIn("[data-open-repair-order-modal]", BOARD_WEB_APP_HTML)
        self.assertIn("openRepairOrderModal();", BOARD_WEB_APP_HTML)
        self.assertNotIn('id="repairOrderEntryNote"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrderDate"', BOARD_WEB_APP_HTML)
        self.assertIn('data-repair-order-field="date" type="text"', BOARD_WEB_APP_HTML)
        self.assertIn('data-repair-order-section="document"', BOARD_WEB_APP_HTML)
        self.assertIn('data-repair-order-section="client"', BOARD_WEB_APP_HTML)
        self.assertIn('data-repair-order-section="vehicle"', BOARD_WEB_APP_HTML)
        self.assertIn('repair-order-card__grid repair-order-card__grid--document', BOARD_WEB_APP_HTML)
        self.assertIn('repair-order-card__grid repair-order-card__grid--client', BOARD_WEB_APP_HTML)
        self.assertIn('repair-order-card__grid repair-order-card__grid--vehicle', BOARD_WEB_APP_HTML)
        self.assertIn('grid-template-columns: minmax(236px, 0.82fr) minmax(332px, 1.04fr) minmax(544px, 1.72fr);', BOARD_WEB_APP_HTML)
        self.assertIn('placeholder="04.04.26 14:30"', BOARD_WEB_APP_HTML)
        self.assertIn('placeholder="Имя и фамилия"', BOARD_WEB_APP_HTML)
        self.assertIn('ИНФОРМАЦИЯ ДЛЯ КЛИЕНТА', BOARD_WEB_APP_HTML)
        self.assertIn('aria-label="Клиент"', BOARD_WEB_APP_HTML)
        self.assertIn('aria-label="Автомобиль"', BOARD_WEB_APP_HTML)
        self.assertIn('aria-label="Информация для клиента"', BOARD_WEB_APP_HTML)
        self.assertIn('Краткая история ремонта для клиента', BOARD_WEB_APP_HTML)
        self.assertNotIn('id="repairOrderModalNote"', BOARD_WEB_APP_HTML)
        self.assertNotIn('<div class="dialog__title-prefix">ЗАКАЗ-НАРЯД</div>', BOARD_WEB_APP_HTML)
        self.assertNotIn('<label for="repairOrderClient">КЛИЕНТ</label>', BOARD_WEB_APP_HTML)
        self.assertNotIn('<label for="repairOrderVehicle">АВТОМОБИЛЬ</label>', BOARD_WEB_APP_HTML)
        self.assertNotIn('<label for="repairOrderComment">ИНФОРМАЦИЯ ДЛЯ КЛИЕНТА</label>', BOARD_WEB_APP_HTML)
        self.assertIn('.repair-order-client-info textarea {', BOARD_WEB_APP_HTML)
        self.assertIn('min-height: 156px;', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrderAddWorkRowButton"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrderAddMaterialRowButton"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrderAutofillButton"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrderPrintButton"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrderTagList"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrderTagInput"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrderTagAddButton"', BOARD_WEB_APP_HTML)
        self.assertIn('data-repair-order-total="works"', BOARD_WEB_APP_HTML)
        self.assertIn('data-repair-order-total="materials"', BOARD_WEB_APP_HTML)
        self.assertIn('data-repair-order-total="grand"', BOARD_WEB_APP_HTML)
        self.assertIn('data-add-repair-order-row="works"', BOARD_WEB_APP_HTML)
        self.assertIn('data-add-repair-order-row="materials"', BOARD_WEB_APP_HTML)
        self.assertIn("function currentRepairOrderDateTime()", BOARD_WEB_APP_HTML)
        self.assertIn("function normalizeRepairOrder(", BOARD_WEB_APP_HTML)
        self.assertIn("function repairOrderRowsTotalValue(", BOARD_WEB_APP_HTML)
        self.assertIn("function syncRepairOrderTotals()", BOARD_WEB_APP_HTML)
        self.assertIn("function addRepairOrderRowFromButton(section, event)", BOARD_WEB_APP_HTML)
        self.assertIn("function handleRepairOrderModalInput(event)", BOARD_WEB_APP_HTML)
        self.assertIn("function renderRepairOrderTags()", BOARD_WEB_APP_HTML)
        self.assertIn("function editRepairOrderTag(label)", BOARD_WEB_APP_HTML)
        self.assertIn("function removeRepairOrderTag(label)", BOARD_WEB_APP_HTML)
        self.assertIn("function handleRepairOrderTagInputKeydown(event)", BOARD_WEB_APP_HTML)
        self.assertIn("function saveRepairOrderDraft()", BOARD_WEB_APP_HTML)
        self.assertIn("function printRepairOrderDraft()", BOARD_WEB_APP_HTML)
        self.assertIn("async function ensureRepairOrderCard()", BOARD_WEB_APP_HTML)
        self.assertIn("async function requireRepairOrderCardId()", BOARD_WEB_APP_HTML)
        self.assertIn("const data = await persistCardPayload(payload);", BOARD_WEB_APP_HTML)
        self.assertIn("applyCardModalState(savedCard);", BOARD_WEB_APP_HTML)
        self.assertIn("function applyRepairOrderCardUpdate(updatedCard, fallbackOrder = {})", BOARD_WEB_APP_HTML)
        self.assertIn("body.insertAdjacentHTML('beforeend', repairOrderRowHtml(section, emptyRepairOrderRow(), rowIndex));", BOARD_WEB_APP_HTML)
        self.assertIn("function saveRepairOrder(", BOARD_WEB_APP_HTML)
        self.assertIn("const cardId = await requireRepairOrderCardId();", BOARD_WEB_APP_HTML)
        self.assertIn("source.client_information ?? source.comment", BOARD_WEB_APP_HTML)
        self.assertIn("function repairOrderCanonicalDateValue(value)", BOARD_WEB_APP_HTML)
        self.assertIn("function repairOrderFormDateDisplayValue(value)", BOARD_WEB_APP_HTML)
        self.assertIn('<section class="print-section"><h2>Информация для клиента</h2>', BOARD_WEB_APP_HTML)
        self.assertIn('Итого к оплате', BOARD_WEB_APP_HTML)
        self.assertIn('print-totals__row--grand', BOARD_WEB_APP_HTML)
        self.assertIn('.repair-order-footer {', BOARD_WEB_APP_HTML)
        self.assertIn('.repair-order-total--grand {', BOARD_WEB_APP_HTML)
        self.assertIn("'/api/autofill_repair_order'", BOARD_WEB_APP_HTML)
        self.assertIn("@page { size: A4; margin: 12mm; }", BOARD_WEB_APP_HTML)
        self.assertIn("printWindow.print();", BOARD_WEB_APP_HTML)

    def test_repair_order_autofill_status_uses_report_hints(self) -> None:
        self.assertIn("function buildRepairOrderAutofillStatus(data)", BOARD_WEB_APP_HTML)
        self.assertIn("data?.meta?.autofill_report", BOARD_WEB_APP_HTML)
        self.assertIn("цены из истории", BOARD_WEB_APP_HTML)

    def test_repair_order_print_module_exposes_preview_template_editor_and_routes(self) -> None:
        self.assertIn('id="repairOrderPrintModal"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrderPrintDocuments"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrderPrintPreviewFrame"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrderPrintTemplateSelect"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrderPrintPrinterSelect"', BOARD_WEB_APP_HTML)
        self.assertIn('id="printProfileOgrn"', BOARD_WEB_APP_HTML)
        self.assertIn('id="printTemplateEditorModal"', BOARD_WEB_APP_HTML)
        self.assertIn('id="printTemplateContent"', BOARD_WEB_APP_HTML)
        self.assertIn('id="printTemplateVisualEditorFrame"', BOARD_WEB_APP_HTML)
        self.assertIn('id="printTemplateTokenSelect"', BOARD_WEB_APP_HTML)
        self.assertIn('id="printTemplatePreviewFrame"', BOARD_WEB_APP_HTML)
        self.assertIn("async function openRepairOrderPrintWorkspace()", BOARD_WEB_APP_HTML)
        self.assertIn("function syncRepairOrderPrintPrinterState()", BOARD_WEB_APP_HTML)
        self.assertIn("function runRepairOrderBrowserPrint()", BOARD_WEB_APP_HTML)
        self.assertIn("function buildPrintTemplateVisualEditorHtml(content)", BOARD_WEB_APP_HTML)
        self.assertIn("'/api/get_repair_order_print_workspace'", BOARD_WEB_APP_HTML)
        self.assertIn("'/api/preview_repair_order_print_documents'", BOARD_WEB_APP_HTML)
        self.assertIn("'/api/export_repair_order_print_pdf'", BOARD_WEB_APP_HTML)
        self.assertIn("'/api/print_repair_order_documents'", BOARD_WEB_APP_HTML)
        self.assertIn("'/api/save_print_template'", BOARD_WEB_APP_HTML)
        self.assertIn("'/api/set_default_print_template'", BOARD_WEB_APP_HTML)
        self.assertIn("printRepairOrderDraft = function() { return openRepairOrderPrintWorkspace(); };", BOARD_WEB_APP_HTML)
        self.assertNotIn("printEls.documents.addEventListener('change', handleRepairOrderPrintDocumentsChange);", BOARD_WEB_APP_HTML)
        self.assertIn("return '<div class=\"repair-order-print-doc' + activeClass + '\" data-print-document=\"' + escapeHtml(item.id) + '\">' +", BOARD_WEB_APP_HTML)
        self.assertNotIn('data-print-document-toggle', BOARD_WEB_APP_HTML)
        self.assertIn("repairOrderPrintState.selectedDocumentIds = [documentId];", BOARD_WEB_APP_HTML)
        self.assertIn("printEls.templateVisualEditorFrame.addEventListener('load', handlePrintTemplateVisualEditorLoad);", BOARD_WEB_APP_HTML)
        self.assertIn("win.print();", BOARD_WEB_APP_HTML)
        self.assertIn('#repairOrderPrintModal {', BOARD_WEB_APP_HTML)
        self.assertIn('#printTemplateEditorModal {', BOARD_WEB_APP_HTML)
        self.assertIn('z-index: 16;', BOARD_WEB_APP_HTML)
        self.assertIn('z-index: 17;', BOARD_WEB_APP_HTML)

    def test_topbar_repair_orders_list_uses_compact_row_open_flow(self) -> None:
        self.assertIn('id="repairOrdersButton"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrdersModal"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrdersList"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrdersTableHead"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrdersSearchInput"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrdersSortBy"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrdersSortDir"', BOARD_WEB_APP_HTML)
        self.assertIn("function openRepairOrdersModal()", BOARD_WEB_APP_HTML)
        self.assertIn("async function handleRepairOrdersListKeydown(event)", BOARD_WEB_APP_HTML)
        self.assertIn("loadRepairOrders = async function(openModal = false)", BOARD_WEB_APP_HTML)
        self.assertIn("function openRepairOrderCard(cardId)", BOARD_WEB_APP_HTML)
        self.assertIn("await openCardWorkspace(cardId, { closeModalEl: els.repairOrdersModal, openRepairOrder: true });", BOARD_WEB_APP_HTML)
        self.assertIn("function repairOrdersRequestPath()", BOARD_WEB_APP_HTML)
        self.assertIn("params.set('status', state.repairOrdersFilter === 'closed' ? 'closed' : 'open');", BOARD_WEB_APP_HTML)
        self.assertIn("params.set('sort_by', normalizeRepairOrdersSortBy(state.repairOrdersSortBy));", BOARD_WEB_APP_HTML)
        self.assertIn("params.set('sort_dir', normalizeRepairOrdersSortDir(state.repairOrdersSortDir));", BOARD_WEB_APP_HTML)
        self.assertIn("if (state.repairOrdersQuery) params.set('query', state.repairOrdersQuery);", BOARD_WEB_APP_HTML)
        self.assertIn("'/api/open_card'", BOARD_WEB_APP_HTML)
        self.assertIn("data-open-repair-order-card", BOARD_WEB_APP_HTML)
        self.assertIn('.dialog--repair-orders {', BOARD_WEB_APP_HTML)
        self.assertIn('width: min(1580px, calc(100% - 18px));', BOARD_WEB_APP_HTML)
        self.assertIn("repairOrderListTotalText(item.grand_total, item.works_total)", BOARD_WEB_APP_HTML)
        self.assertIn("function repairOrderListDateDisplayValue(value)", BOARD_WEB_APP_HTML)
        self.assertIn("renderRepairOrderListRows = function(items)", BOARD_WEB_APP_HTML)
        self.assertIn(".repair-orders-row__number", BOARD_WEB_APP_HTML)
        self.assertIn(".repair-orders-row__opened", BOARD_WEB_APP_HTML)
        self.assertIn(".repair-orders-row__closed", BOARD_WEB_APP_HTML)
        self.assertIn(".repair-orders-row__status", BOARD_WEB_APP_HTML)
        self.assertIn(".repair-orders-row__client", BOARD_WEB_APP_HTML)
        self.assertIn(".repair-orders-row__phone", BOARD_WEB_APP_HTML)
        self.assertIn(".repair-orders-row__vehicle", BOARD_WEB_APP_HTML)
        self.assertIn(".repair-orders-row__title", BOARD_WEB_APP_HTML)
        self.assertIn(".repair-orders-row__tags", BOARD_WEB_APP_HTML)
        self.assertIn(".repair-orders-table-head", BOARD_WEB_APP_HTML)
        self.assertIn(".repair-orders-table-head__sum", BOARD_WEB_APP_HTML)
        self.assertIn(".repair-orders-row__total", BOARD_WEB_APP_HTML)
        self.assertIn("function repairOrdersColumnsValue(status = state.repairOrdersFilter)", BOARD_WEB_APP_HTML)
        self.assertIn("function repairOrdersTableHeadHtml(status = state.repairOrdersFilter)", BOARD_WEB_APP_HTML)
        self.assertIn("function syncRepairOrdersLayout(status = state.repairOrdersFilter)", BOARD_WEB_APP_HTML)
        self.assertIn("СПИСОК: ДАТА / АВТО / СУТЬ / СУММА", BOARD_WEB_APP_HTML)
        self.assertIn("Открыта", BOARD_WEB_APP_HTML)
        self.assertIn("Телефон", BOARD_WEB_APP_HTML)
        self.assertIn("Автомобиль", BOARD_WEB_APP_HTML)
        self.assertIn("Смысл карточки", BOARD_WEB_APP_HTML)
        self.assertIn("Сумма", BOARD_WEB_APP_HTML)
        self.assertIn("return canonical.split(' ')[0] || canonical;", BOARD_WEB_APP_HTML)
        self.assertIn("item.opened_at || item.created_at || item.date || item.updated_at", BOARD_WEB_APP_HTML)
        self.assertIn("item.grand_total, item.works_total", BOARD_WEB_APP_HTML)
        self.assertIn("els.repairOrdersButton.addEventListener('click', openRepairOrdersModal);", BOARD_WEB_APP_HTML)
        self.assertIn("els.repairOrdersList.addEventListener('keydown', handleRepairOrdersListKeydown);", BOARD_WEB_APP_HTML)
        self.assertIn("els.repairOrdersSearchInput.addEventListener('input', handleRepairOrdersSearchInput);", BOARD_WEB_APP_HTML)
        self.assertIn("els.repairOrdersSortBy.addEventListener('change', handleRepairOrdersSortChange);", BOARD_WEB_APP_HTML)
        self.assertIn("els.repairOrdersSortDir.addEventListener('change', handleRepairOrdersSortChange);", BOARD_WEB_APP_HTML)

    def test_repair_order_modal_supports_status_and_extended_vehicle_fields(self) -> None:
        self.assertIn('id="repairOrderOpenedAt"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrderClosedAt"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrderStatus"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrderVin"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrderMileage"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrderReason"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrderNote"', BOARD_WEB_APP_HTML)
        self.assertIn('repair-order-card repair-order-card--wide hidden" data-repair-order-section="reason"', BOARD_WEB_APP_HTML)
        self.assertIn('repair-order-card repair-order-card--wide hidden" data-repair-order-section="note"', BOARD_WEB_APP_HTML)
        self.assertIn('repair-order-card repair-order-card--wide repair-order-tags-card hidden" data-repair-order-section="tags"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrderCloseButton"', BOARD_WEB_APP_HTML)
        self.assertIn("function repairOrderStatusLabel(status)", BOARD_WEB_APP_HTML)
        self.assertIn("function repairOrderCardDraft(card, order = {})", BOARD_WEB_APP_HTML)
        self.assertIn("function syncRepairOrderStatusUi(status)", BOARD_WEB_APP_HTML)
        self.assertIn("async function persistRepairOrderRecord({ statusMessage = '', silent = false } = {})", BOARD_WEB_APP_HTML)
        self.assertIn("'/api/update_repair_order'", BOARD_WEB_APP_HTML)
        self.assertIn("async function toggleRepairOrderStatus()", BOARD_WEB_APP_HTML)
        self.assertIn("'/api/set_repair_order_status'", BOARD_WEB_APP_HTML)
        self.assertIn("els.repairOrderCloseButton.addEventListener('click', toggleRepairOrderStatus);", BOARD_WEB_APP_HTML)

    def test_repair_orders_menu_supports_open_and_closed_filters(self) -> None:
        self.assertIn('id="repairOrdersOpenTab"', BOARD_WEB_APP_HTML)
        self.assertIn('id="repairOrdersClosedTab"', BOARD_WEB_APP_HTML)
        self.assertIn("function updateRepairOrdersTabs()", BOARD_WEB_APP_HTML)
        self.assertIn("renderRepairOrderListRows = function(items)", BOARD_WEB_APP_HTML)
        self.assertIn("async function setRepairOrdersFilter(status, { openModal = false } = {})", BOARD_WEB_APP_HTML)
        self.assertIn("syncRepairOrdersLayout(isClosed ? 'closed' : 'open');", BOARD_WEB_APP_HTML)
        self.assertIn("ОТКРЫТЫЕ: ", BOARD_WEB_APP_HTML)
        self.assertIn("АРХИВ: ", BOARD_WEB_APP_HTML)
        self.assertIn("repairOrdersIsClosedView(status)", BOARD_WEB_APP_HTML)
        self.assertIn("const phoneText = phone || '-';", BOARD_WEB_APP_HTML)
        self.assertIn("Статус", BOARD_WEB_APP_HTML)
        self.assertIn("Телефон", BOARD_WEB_APP_HTML)
        self.assertIn("item.opened_at || item.created_at || item.date || item.updated_at", BOARD_WEB_APP_HTML)
        self.assertIn("item.grand_total, item.works_total", BOARD_WEB_APP_HTML)
        self.assertIn("els.repairOrdersOpenTab.addEventListener('click', () => setRepairOrdersFilter('open'));", BOARD_WEB_APP_HTML)
        self.assertIn("els.repairOrdersClosedTab.addEventListener('click', () => setRepairOrdersFilter('closed'));", BOARD_WEB_APP_HTML)

    def test_cashboxes_modal_exposes_minimal_accounting_workspace(self) -> None:
        self.assertIn('id="cashboxesButton"', BOARD_WEB_APP_HTML)
        self.assertIn('id="cashboxesModal"', BOARD_WEB_APP_HTML)
        self.assertIn('id="cashboxesList"', BOARD_WEB_APP_HTML)
        self.assertIn('id="cashboxCreateButton"', BOARD_WEB_APP_HTML)
        self.assertIn('id="cashboxIncomeButton"', BOARD_WEB_APP_HTML)
        self.assertIn('id="cashboxExpenseButton"', BOARD_WEB_APP_HTML)
        self.assertIn('id="cashboxTransactions"', BOARD_WEB_APP_HTML)
        self.assertIn(".cashboxes-layout {", BOARD_WEB_APP_HTML)
        self.assertIn("function openCashboxesModal()", BOARD_WEB_APP_HTML)
        self.assertIn("async function createCashbox()", BOARD_WEB_APP_HTML)
        self.assertIn("async function createCashboxTransaction(direction)", BOARD_WEB_APP_HTML)
        self.assertIn("async function loadCashboxes(openModal = false)", BOARD_WEB_APP_HTML)
        self.assertIn("async function loadCashboxDetail(cashboxId, { openModal = false } = {})", BOARD_WEB_APP_HTML)
        self.assertIn("els.cashboxesButton.addEventListener('click', openCashboxesModal);", BOARD_WEB_APP_HTML)
        self.assertIn("data-close=\"cashboxes\"", BOARD_WEB_APP_HTML)

    def test_modal_data_loader_helpers_drive_active_archive_and_gpt_paths(self) -> None:
        self.assertIn("function maybeOpenModal(modalEl, openModal)", BOARD_WEB_APP_HTML)
        self.assertIn("function openArchiveModal()", BOARD_WEB_APP_HTML)
        self.assertIn("renderArchive();", BOARD_WEB_APP_HTML)
        self.assertIn("function handleBoardScaleInput()", BOARD_WEB_APP_HTML)
        self.assertIn("async function resetBoardScaleToDefault()", BOARD_WEB_APP_HTML)
        self.assertIn("async function persistBoardScaleChange()", BOARD_WEB_APP_HTML)
        self.assertIn("function openBoardSettings()", BOARD_WEB_APP_HTML)
        self.assertIn("function openGptWallModal()", BOARD_WEB_APP_HTML)
        self.assertIn("function refreshGptWallView()", BOARD_WEB_APP_HTML)
        self.assertIn("async function createColumnFromTopbar()", BOARD_WEB_APP_HTML)
        self.assertIn("function closeNamedModal(closeKey)", BOARD_WEB_APP_HTML)
        self.assertIn("async function loadModalData(path, { method = 'GET', body = null, openModal = false, modalEl = null, onSuccess, onError } = {})", BOARD_WEB_APP_HTML)
        self.assertIn("async function reloadOperatorAdminUsers({ openModal = false } = {})", BOARD_WEB_APP_HTML)
        self.assertIn("loadGptWall = async function(openModal = false)", BOARD_WEB_APP_HTML)
        self.assertIn("renderCompactArchiveRows(cards)", BOARD_WEB_APP_HTML)
        self.assertIn("renderRepairOrderListRows(items)", BOARD_WEB_APP_HTML)
        self.assertIn("repairOrdersMetaText = function(items, meta)", BOARD_WEB_APP_HTML)
        self.assertIn("function gptWallMetaText(meta)", BOARD_WEB_APP_HTML)
        self.assertIn("function normalizeGptWallView(value)", BOARD_WEB_APP_HTML)
        self.assertIn("function buildReadableGptWallEvents(data)", BOARD_WEB_APP_HTML)
        self.assertIn("function renderGptWallView()", BOARD_WEB_APP_HTML)
        self.assertIn("id=\"gptWallBoardTab\"", BOARD_WEB_APP_HTML)
        self.assertIn("id=\"gptWallEventsTab\"", BOARD_WEB_APP_HTML)
        self.assertIn("function setModalListError(metaEl, listEl, metaText, bodyText)", BOARD_WEB_APP_HTML)
        self.assertIn("function setModalTextError(metaEl, textEl, metaText, bodyText)", BOARD_WEB_APP_HTML)
        self.assertIn("lastSnapshotRevision: ''", BOARD_WEB_APP_HTML)
        self.assertIn("const previousRevision = String(state.lastSnapshotRevision || '');", BOARD_WEB_APP_HTML)
        self.assertIn("const nextRevision = String(nextSnapshot?.meta?.revision || '');", BOARD_WEB_APP_HTML)
        self.assertIn("const boardChanged = !previousRevision || !nextRevision || previousRevision !== nextRevision;", BOARD_WEB_APP_HTML)
        self.assertIn("if (boardChanged) {", BOARD_WEB_APP_HTML)
        self.assertIn("state.lastSnapshotRevision = nextRevision;", BOARD_WEB_APP_HTML)
        self.assertIn("function sortedCardsForBoardColumn(snapshot, columnId)", BOARD_WEB_APP_HTML)
        self.assertIn("function renderBoardColumnHtml(column, index, snapshot)", BOARD_WEB_APP_HTML)
        self.assertIn("function renderBoardColumnById(columnId)", BOARD_WEB_APP_HTML)
        self.assertIn("renderBoardColumnHtml(column, index, snapshot)", BOARD_WEB_APP_HTML)
        self.assertIn("function boardCardElementById(cardId)", BOARD_WEB_APP_HTML)
        self.assertIn("function replaceBoardCardElement(nextCard)", BOARD_WEB_APP_HTML)
        self.assertIn("function applyBoardColumnCardsPatch(nextCards, affectedColumnIds)", BOARD_WEB_APP_HTML)
        self.assertIn("function applyArchivedCardPatch(nextCard)", BOARD_WEB_APP_HTML)
        self.assertIn("const previousCard = snapshotCardById(nextCard.id);", BOARD_WEB_APP_HTML)
        self.assertIn("if (previousColumnId && previousColumnId === nextColumnId) {", BOARD_WEB_APP_HTML)
        self.assertIn("const samePosition = previousPosition === nextPosition || (Number.isNaN(previousPosition) && Number.isNaN(nextPosition));", BOARD_WEB_APP_HTML)
        self.assertIn("if (samePosition && replaceBoardCardElement(nextCard)) return;", BOARD_WEB_APP_HTML)
        self.assertIn("renderBoardColumnById(previousColumnId)", BOARD_WEB_APP_HTML)
        self.assertIn("const patched = applyBoardColumnCardsPatch(data?.affected_cards || [], data?.affected_column_ids || []);", BOARD_WEB_APP_HTML)
        self.assertIn("if (!patched && data?.card) {", BOARD_WEB_APP_HTML)
        self.assertIn("if (data?.card && applyArchivedCardPatch(data.card)) return;", BOARD_WEB_APP_HTML)

    def test_web_assets_do_not_keep_duplicate_active_function_names(self) -> None:
        self.assertEqual(BOARD_WEB_APP_HTML.count("function buildVehicleAutofillRawText()"), 1)
        self.assertEqual(BOARD_WEB_APP_HTML.count("function refreshVehiclePanel()"), 1)
        self.assertEqual(BOARD_WEB_APP_HTML.count("async function saveCard()"), 1)
        self.assertEqual(BOARD_WEB_APP_HTML.count("repairOrdersMetaText = function(items, meta)"), 1)
        self.assertEqual(BOARD_WEB_APP_HTML.count("function renderRepairOrderRows(items)"), 0)
        self.assertEqual(BOARD_WEB_APP_HTML.count("function renderRepairOrderRows(section, rows)"), 1)
        self.assertEqual(BOARD_WEB_APP_HTML.count("renderRepairOrderListRows = function(items)"), 1)
        self.assertEqual(BOARD_WEB_APP_HTML.count("loadRepairOrders = async function(openModal = false)"), 1)
        self.assertIn("if (target.dataset.close) closeNamedModal(target.dataset.close);", BOARD_WEB_APP_HTML)
        self.assertIn("els.archiveButton.addEventListener('click', openArchiveModal);", BOARD_WEB_APP_HTML)
        self.assertIn("els.boardSettingsButton.addEventListener('click', openBoardSettings);", BOARD_WEB_APP_HTML)
        self.assertIn("els.boardScaleInput.addEventListener('input', handleBoardScaleInput);", BOARD_WEB_APP_HTML)
        self.assertIn("els.boardScaleInput.addEventListener('change', persistBoardScaleChange);", BOARD_WEB_APP_HTML)
        self.assertIn("els.boardScaleReset.addEventListener('click', resetBoardScaleToDefault);", BOARD_WEB_APP_HTML)
        self.assertIn("els.gptWallButton.addEventListener('click', openGptWallModal);", BOARD_WEB_APP_HTML)
        self.assertIn("els.gptWallBoardTab.addEventListener('click', () => setGptWallView('board_content'));", BOARD_WEB_APP_HTML)
        self.assertIn("els.gptWallEventsTab.addEventListener('click', () => setGptWallView('event_log'));", BOARD_WEB_APP_HTML)
        self.assertIn("els.gptWallRefresh.addEventListener('click', refreshGptWallView);", BOARD_WEB_APP_HTML)
        self.assertIn("els.gptWallText.dataset.wallView = view;", BOARD_WEB_APP_HTML)
        self.assertIn("els.columnButton.addEventListener('click', createColumnFromTopbar);", BOARD_WEB_APP_HTML)

    def test_blob_helpers_drive_download_and_text_report_paths(self) -> None:
        self.assertIn("function withObjectUrl(blob, callback, { revokeDelay = 1500 } = {})", BOARD_WEB_APP_HTML)
        self.assertIn("function triggerBlobDownload(blob, fileName)", BOARD_WEB_APP_HTML)
        self.assertIn("triggerBlobDownload(blob, extractDownloadName(response, 'attachment.bin'));", BOARD_WEB_APP_HTML)
        self.assertIn("withObjectUrl(blob, (objectUrl) => {", BOARD_WEB_APP_HTML)
        self.assertIn("const opened = window.open(objectUrl, '_blank', 'noopener');", BOARD_WEB_APP_HTML)

    def test_card_preview_clean_russian_labels_override_broken_legacy_copy(self) -> None:
        self.assertIn("БЕЗ МЕТОК", BOARD_WEB_APP_HTML)
        self.assertIn("Описание не указано", BOARD_WEB_APP_HTML)
        self.assertIn("СИГН", BOARD_WEB_APP_HTML)
        self.assertIn("ФАЙЛЫ ", BOARD_WEB_APP_HTML)
        self.assertIn("ЖУРНАЛ ", BOARD_WEB_APP_HTML)
        self.assertIn('title="Не прочитано"', BOARD_WEB_APP_HTML)


if __name__ == "__main__":
    unittest.main()
