from __future__ import annotations

MCP_TOOL_GROUPS: dict[str, tuple[str, ...]] = {
    "diagnostics_bootstrap": (
        "bootstrap_context",
        "get_board_content",
        "get_board_context",
        "get_board_events",
        "get_connector_identity",
        "get_gpt_wall",
        "get_runtime_status",
        "ping_connector",
        "review_board",
    ),
    "manager_operations": (
        "manager_board_scan",
        "list_ready_unpaid_cards",
        "triage_inbox_cards",
        "list_cards_missing_manager_data",
        "audit_repair_order_consistency",
        "audit_client_links",
        "bulk_set_deadline_if_below",
        "bulk_refresh_board_summaries",
        "cleanup_card",
        "apply_ready_unpaid_followups",
        "run_manager_operation",
        "rollback_manager_run",
    ),
    "board_cards": (
        "archive_card",
        "bulk_move_cards",
        "create_card",
        "create_column",
        "create_sticky",
        "delete_column",
        "delete_sticky",
        "get_board_snapshot",
        "get_card",
        "get_card_attachment",
        "get_card_context",
        "get_card_log",
        "get_cards",
        "list_archived_cards",
        "list_card_attachments",
        "list_columns",
        "list_overdue_cards",
        "mark_card_ready",
        "move_card",
        "move_sticky",
        "read_card_attachment",
        "rename_column",
        "restore_card",
        "search_cards",
        "set_card_board_summary",
        "set_card_deadline",
        "set_card_indicator",
        "update_board_settings",
        "update_card",
        "update_sticky",
    ),
    "clients": (
        "create_client",
        "delete_client",
        "delete_client_vehicle",
        "get_client",
        "get_client_stats",
        "link_card_to_client",
        "list_clients",
        "search_clients",
        "suggest_clients_for_card",
        "unlink_card_from_client",
        "update_client",
        "upsert_client_vehicle",
    ),
    "repair_orders": (
        "download_repair_order_print_pdf",
        "get_repair_order",
        "get_repair_order_text",
        "list_repair_orders",
        "replace_repair_order_materials",
        "replace_repair_order_works",
        "set_repair_order_status",
        "update_repair_order",
    ),
    "cashboxes": (
        "create_cash_transaction",
        "create_cashbox",
        "delete_cashbox",
        "get_cash_journal",
        "get_cashbox",
        "list_cashboxes",
    ),
    "inventory": (
        "get_inventory_item",
        "list_inventory_items",
        "list_inventory_movements",
        "replenish_inventory_item",
        "return_inventory_movement",
        "save_inventory_item",
        "search_inventory_items",
        "write_off_inventory_item",
    ),
    "files": (
        "delete_shared_file",
        "download_shared_file",
        "get_shared_file_info",
        "list_shared_files",
        "update_shared_file_position",
        "upload_shared_file",
    ),
}

PUBLIC_MCP_TOOL_NAMES = frozenset(
    tool_name for group in MCP_TOOL_GROUPS.values() for tool_name in group
)

__all__ = ["MCP_TOOL_GROUPS", "PUBLIC_MCP_TOOL_NAMES"]
