    function ensureEmployeesUi() {
      if (document.getElementById('employeesModal')) return;
      document.body.insertAdjacentHTML(
        'beforeend',
        ''
          + '<div class="modal" id="employeesModal">'
            + '<div class="dialog dialog--employees dialog--fixed-actions">'
              + '<div class="dialog__head dialog__floating-actions">'
                + '<div class="dialog__title">СОТРУДНИКИ</div>'
                + '<div class="employees-dialog-actions">'
                  + '<button class="btn btn--ghost" id="employeesCreateButton" type="button">ДОБАВИТЬ</button>'
                  + '<button class="btn" data-close="employees">ЗАКРЫТЬ</button>'
                + '</div>'
              + '</div>'
              + '<div class="dialog__body-scroll employees-layout">'
                + '<div class="employees-pane employees-pane--list">'
                  + '<div class="subpanel">'
                    + '<div class="employees-panel-head">'
                      + '<div class="panel-title">СПИСОК СОТРУДНИКОВ</div>'
                      + '</div>'
                    + '</div>'
                    + '<div class="employees-list" id="employeesList"></div>'
                  + '</div>'
                + '<div class="employees-pane">'
                  + '<div class="subpanel" id="employeesProfilePanel">'
                    + '<div class="employees-card-head dialog__floating-actions">'
                      + '<div class="employees-card-head-main">'
                        + '<div class="panel-title">ПРОФИЛЬ</div>'
                        + '<div class="employees-card-title"><strong id="employeesCardMode">НОВЫЙ СОТРУДНИК</strong></div>'
                      + '</div>'
                      + '<div class="employees-card-actions">'
                        + '<button class="btn btn--ghost" id="employeeSaveButton" type="button">СОХРАНИТЬ</button>'
                        + '<button class="btn btn--ghost" id="employeeDeleteButton" type="button">УВОЛИТЬ СОТРУДНИКА</button>'
                      + '</div>'
                    + '</div>'
                    + '<div class="employees-form-grid">'
                      + '<div class="field employees-field--span-4"><label for="employeeNameInput">ИМЯ</label><input id="employeeNameInput" type="text" maxlength="80"></div>'
                      + '<div class="field employees-field--span-4"><label for="employeeMiddleNameInput">ОТЧЕСТВО</label><input id="employeeMiddleNameInput" type="text" maxlength="80"></div>'
                      + '<div class="field employees-field--span-4"><label for="employeePositionInput">ДОЛЖНОСТЬ</label><input id="employeePositionInput" type="text" maxlength="80"></div>'
                      + '<input id="employeeSalaryModeInput" type="hidden" value="percent_only">'
                      + '<input id="employeeBaseSalaryInput" type="hidden" value="">'
                      + '<input id="employeeWorkPercentInput" type="hidden" value="">'
                      + '<input id="employeeMaterialPercentInput" type="hidden" value="">'
                      + '<input id="employeeRepairOrderPercentInput" type="hidden" value="">'
                      + '<div class="employees-incentives" id="employeeIncentivesPanel">'
                        + '<div class="employees-incentives__head">'
                          + '<div class="panel-title">НАЧИСЛЕНИЯ</div>'
                          + '<div class="employees-incentives__actions">'
                            + '<button class="btn btn--ghost" id="employeeShiftAccrualButton" type="button">+ СМЕНЫ</button>'
                            + '<div class="employees-incentives__choices" id="employeeIncentiveAddChoices"></div>'
                          + '</div>'
                        + '</div>'
                        + '<div class="employees-incentives__list" id="employeeIncentivesList"></div>'
                        + '<div class="employees-salary-dialog employees-shift-dialog" id="employeeShiftAccrualDialog" hidden>'
                          + '<div class="employees-salary-dialog__head">'
                            + '<div class="panel-title">ВЫПЛАТА ЗА СМЕНЫ</div>'
                            + '<button class="btn btn--ghost" id="employeeShiftAccrualCancelButton" type="button">ОТМЕНА</button>'
                          + '</div>'
                          + '<div class="employees-salary-dialog__body">'
                            + '<div class="field employees-field--compact employees-field--salary"><label for="employeeShiftAccrualAmountInput">СУММА</label><input id="employeeShiftAccrualAmountInput" type="text" inputmode="decimal" maxlength="40" placeholder="0"></div>'
                            + '<button class="btn btn--accent" id="employeeShiftAccrualConfirmButton" type="button">НАЧИСЛИТЬ</button>'
                          + '</div>'
                        + '</div>'
                      + '</div>'
                    + '</div>'
                  + '</div>'
                  + '<div class="subpanel employees-read-only-notice" id="employeesReadOnlyNotice" hidden>'
                    + '<div class="panel-title">ТОЛЬКО ПРОСМОТР</div>'
                    + '<div class="log-row__meta">Доступен только список активных сотрудников. Зарплаты, начисления, отчёты и изменение данных закрыты.</div>'
                  + '</div>'
                  + '<div class="subpanel" id="employeesReportPanel">'
                    + '<div class="employees-panel-head"><div class="panel-title">ОТЧЁТ ПО СОТРУДНИКУ</div><input class="repair-orders-search" id="employeesMonthInput" type="month"></div>'
              + '<div class="employees-report-shell" id="employeesReportShell">'
                + '<div class="employees-report-panel employees-report-panel--details is-collapsed" id="employeesDetailsPanel">'
                  + '<div class="employees-report-panel__head">'
                    + '<div class="employees-report-panel__title">ДЕТАЛИЗАЦИЯ</div>'
                    + '<div class="employees-report-panel__meta" id="employeesReportMeta">Выберите сотрудника слева, чтобы открыть детализацию.</div>'
                  + '</div>'
                  + '<div class="employees-report-panel__meta" id="employeesDetailsMeta">Отчёт откроется после выбора сотрудника.</div>'
                  + '<div class="employees-table-wrap employees-table-wrap--details"><table class="employees-table"><thead><tr><th>ДАТА</th><th>НАРЯД</th><th>АВТО</th><th>ТИП</th><th>ПОЗИЦИЯ</th><th class="is-num">ПРОДАЖА</th><th class="is-num">ЗАКУПКА</th><th class="is-num">ПРИБЫЛЬ</th><th class="is-num">НАЧИСЛЕНО</th></tr></thead><tbody id="employeesDetailTable"></tbody></table></div>'
                + '</div>'
              + '</div>'
                    + '</div>'
                  + '</div>'
                + '</div>'
              + '</div>'
            + '</div>'
          + '</div>'
          + '<div class="modal" id="employeeSalaryModal">'
            + '<div class="dialog dialog--salary" style="width:min(980px,100%);">'
              + '<div class="dialog__head">'
                + '<div class="dialog__title">ЗАРПЛАТА / <span id="employeeSalaryTitle">СОТРУДНИК</span></div>'
                + '<button class="btn" data-close="employeeSalary">ЗАКРЫТЬ</button>'
              + '</div>'
              + '<div class="employees-salary-head">'
                + '<div class="employees-salary-balance">'
                  + '<div class="employees-salary-balance__label">БАЛАНС</div>'
                  + '<div class="employees-salary-balance__value" id="employeeSalaryBalance">0</div>'
                + '</div>'
                + '<div class="employees-salary-actions">'
                  + '<button class="btn btn--danger hidden" id="employeeSalaryResetButton" type="button">ОБНУЛИТЬ БАЛАНС</button>'
                  + '<button class="btn btn--accent" id="employeeSalaryPayoutButton" type="button">ВЫПЛАТИТЬ ЗАРПЛАТУ</button>'
                  + '<button class="btn btn--accent" id="employeeSalaryAdvanceButton" type="button">ВЫДАТЬ АВАНС</button>'
                + '</div>'
              + '</div>'
              + '<div class="employees-salary-summary" id="employeeSalarySummary"></div>'
              + '<div class="employees-salary-journal">'
                + '<div class="employees-salary-journal__head">'
                  + '<div class="panel-title">ЖУРНАЛ ЗА 6 МЕС.</div>'
                  + '<div class="employees-salary-journal__meta" id="employeeSalaryJournalMeta"></div>'
                + '</div>'
                + '<div class="employees-table-wrap">'
                  + '<table class="employees-table employees-salary-table">'
                    + '<thead><tr><th>ДАТА</th><th>ТИП</th><th>НАРЯД</th><th>АВТО</th><th>РАБОТА</th><th>КОММЕНТАРИЙ</th><th class="is-num">СУММА</th></tr></thead>'
                    + '<tbody id="employeeSalaryJournalTable"></tbody>'
                  + '</table>'
                + '</div>'
              + '</div>'
              + '<div class="employees-salary-dialog" id="employeeSalaryActionDialog" hidden>'
                + '<div class="employees-salary-dialog__head">'
                  + '<div class="panel-title" id="employeeSalaryActionTitle">ВЫПЛАТА ЗАРПЛАТЫ</div>'
                  + '<button class="btn btn--ghost" id="employeeSalaryActionCancelButton" type="button">ОТМЕНА</button>'
                + '</div>'
                + '<div class="employees-salary-dialog__body">'
                  + '<div class="field employees-field--compact employees-field--salary"><label for="employeeSalaryAmountInput">СУММА</label><input id="employeeSalaryAmountInput" type="text" inputmode="decimal" maxlength="40" placeholder="0"></div>'
                  + '<div class="field employees-field--compact employees-field--salary"><label for="employeeSalaryCashboxSelect">КАССА</label><select id="employeeSalaryCashboxSelect"></select></div>'
                  + '<button class="btn btn--accent" id="employeeSalaryActionConfirmButton" type="button">ВЫПЛАТИТЬ</button>'
                + '</div>'
              + '</div>'
              + '<div class="employees-salary-dialog" id="employeeSalaryAdvanceDialog" hidden>'
                + '<div class="employees-salary-dialog__head">'
                  + '<div class="panel-title" id="employeeSalaryAdvanceTitle">АВАНС</div>'
                  + '<button class="btn btn--ghost" id="employeeSalaryAdvanceCancelButton" type="button">ОТМЕНА</button>'
                + '</div>'
                + '<div class="employees-salary-dialog__body">'
                  + '<div class="field employees-field--compact employees-field--salary"><label for="employeeSalaryAdvanceAmountInput">СУММА</label><input id="employeeSalaryAdvanceAmountInput" type="text" inputmode="decimal" maxlength="40" placeholder="0"></div>'
                  + '<div class="field employees-field--compact employees-field--salary"><label for="employeeSalaryAdvanceCashboxSelect">КАССА</label><select id="employeeSalaryAdvanceCashboxSelect"></select></div>'
                  + '<div class="field employees-field--compact employees-field--salary employees-salary-dialog__wide"><label for="employeeSalaryAdvanceCommentInput">КОММЕНТАРИЙ</label><input id="employeeSalaryAdvanceCommentInput" type="text" maxlength="240" placeholder="Под что выдается аванс"></div>'
                  + '<button class="btn btn--accent" id="employeeSalaryAdvanceConfirmButton" type="button">ВЫДАТЬ АВАНС</button>'
                + '</div>'
              + '</div>'
            + '</div>'
          + '</div>'
          + '<div class="modal" id="employeeSalaryReconciliationPeriodModal">'
            + '<div class="dialog dialog--salary-report-period">'
              + '<div class="dialog__head">'
                + '<div class="dialog__title">ОТЧЕТ / <span id="employeeSalaryReconciliationPeriodTitle">СОТРУДНИК</span></div>'
                + '<button class="btn" data-close="employee-salary-reconciliation-period">ЗАКРЫТЬ</button>'
              + '</div>'
              + '<div class="employees-report-period employees-report-period--dialog" id="employeeSalaryReconciliationPeriod">'
                + '<div class="employees-report-period__head">'
                  + '<div class="panel-title">ПЕРИОД АКТА</div>'
                  + '<select class="employees-report-period__mode" id="employeeSalaryReconciliationPeriodMode" aria-label="Режим периода акта сверки зарплаты">'
                    + '<option value="days">ПОСЛЕДНИЕ ДНИ</option>'
                    + '<option value="dates">ДАТЫ</option>'
                  + '</select>'
                + '</div>'
                + '<div class="employees-report-period__controls">'
                  + '<label class="employees-report-period__field" id="employeeSalaryReconciliationDaysField" for="employeeSalaryReconciliationDaysInput"><span>ДНЕЙ</span><input id="employeeSalaryReconciliationDaysInput" type="number" inputmode="numeric" min="1" max="366" step="1" value="30"></label>'
                  + '<label class="employees-report-period__field employees-report-period__date" id="employeeSalaryReconciliationDateFromField" for="employeeSalaryReconciliationDateFromInput" hidden><span>С</span><input id="employeeSalaryReconciliationDateFromInput" type="date"></label>'
                  + '<label class="employees-report-period__field employees-report-period__date" id="employeeSalaryReconciliationDateToField" for="employeeSalaryReconciliationDateToInput" hidden><span>ПО</span><input id="employeeSalaryReconciliationDateToInput" type="date"></label>'
                + '</div>'
                + '<div class="employees-report-period__actions">'
                  + '<button class="btn btn--accent" id="employeeSalaryReconciliationOpenButton" type="button">ОТКРЫТЬ ОТЧЕТ</button>'
                  + '<button class="btn btn--ghost" id="employeeSalaryReconciliationCancelButton" type="button">ОТМЕНА</button>'
                + '</div>'
              + '</div>'
            + '</div>'
          + '</div>'
          + '<div class="modal" id="employeeSalaryReportModal">'
            + '<div class="dialog dialog--salary-report">'
              + '<div class="dialog__head">'
                + '<div class="dialog__title">ОТЧЁТ ПО НАЧИСЛЕНИЯМ / <span id="employeeSalaryReportTitle">СОТРУДНИК</span></div>'
                + '<div style="display:flex; gap:8px; flex-wrap:wrap;">'
                  + '<button class="btn btn--ghost" id="employeeSalaryReportDownloadButton" type="button">СКАЧАТЬ .MD</button>'
                  + '<button class="btn" data-close="employee-salary-report">ЗАКРЫТЬ</button>'
                + '</div>'
              + '</div>'
              + '<div class="employee-salary-report" id="employeeSalaryReportRoot">'
                + '<div class="employee-salary-report__meta" id="employeeSalaryReportMeta">ЗАГРУЗКА...</div>'
                + '<pre class="employee-salary-report__text" id="employeeSalaryReportText">ЗАГРУЗКА...</pre>'
              + '</div>'
            + '</div>'
          + '</div>'
      );
    }
