"""Public facade for the AutoStop CRM board web application assets."""

from .web_app_assets.assembler import (
    BOARD_WEB_APP_CONTRACT_TEXT,
    BOARD_WEB_APP_CSS,
    BOARD_WEB_APP_CSS_PATH,
    BOARD_WEB_APP_HTML,
    BOARD_WEB_APP_JS,
    BOARD_WEB_APP_JS_PATH,
    BOARD_WEB_APP_MODULE_MANIFEST,
    BOARD_WEB_APP_MODULES,
    DISPLAY_DASHBOARD_HTML,
    MODULE_MAP_HTML,
    MODULE_MAP_INFRASTRUCTURE,
)

__all__ = [
    "BOARD_WEB_APP_CONTRACT_TEXT",
    "BOARD_WEB_APP_CSS",
    "BOARD_WEB_APP_CSS_PATH",
    "BOARD_WEB_APP_HTML",
    "BOARD_WEB_APP_JS",
    "BOARD_WEB_APP_JS_PATH",
    "BOARD_WEB_APP_MODULES",
    "BOARD_WEB_APP_MODULE_MANIFEST",
    "DISPLAY_DASHBOARD_HTML",
    "MODULE_MAP_HTML",
    "MODULE_MAP_INFRASTRUCTURE",
]
