from __future__ import annotations

from collections.abc import Callable
from typing import Any

RouteHandler = Callable[[dict[str, Any] | None], dict[str, Any]]


PROXIED_WRITE_ROUTES = {
    "/api/create_card",
    "/api/create_column",
    "/api/rename_column",
    "/api/move_column",
    "/api/delete_column",
    "/api/create_cashbox",
    "/api/reorder_cashboxes",
    "/api/create_cashbox_transfer",
    "/api/save_employee",
    "/api/toggle_employee",
    "/api/delete_employee",
    "/api/create_client",
    "/api/update_client",
    "/api/delete_client",
    "/api/link_card_to_client",
    "/api/unlink_card_from_client",
    "/api/upsert_client_vehicle",
    "/api/delete_client_vehicle",
    "/api/delete_cashbox",
    "/api/create_cash_transaction",
    "/api/save_inventory_item",
    "/api/replenish_inventory_item",
    "/api/write_off_inventory_item",
    "/api/return_inventory_movement",
    "/api/create_employee_salary_transaction",
    "/api/create_employee_shift_accrual",
    "/api/cancel_cash_transaction",
    "/api/cancel_last_cash_transaction",
    "/api/finance_audit/apply_safe_fixes",
    "/api/create_sticky",
    "/api/autofill_repair_order",
    "/api/agent_enqueue_task",
    "/api/save_agent_scheduled_task",
    "/api/delete_agent_scheduled_task",
    "/api/pause_agent_scheduled_task",
    "/api/resume_agent_scheduled_task",
    "/api/run_agent_scheduled_task",
    "/api/run_full_card_enrichment",
    "/api/cleanup_card_content",
    "/api/bulk_set_deadline_if_below",
    "/api/bulk_refresh_board_summaries",
    "/api/cleanup_card",
    "/api/apply_ready_unpaid_followups",
    "/api/run_manager_operation",
    "/api/rollback_manager_run",
    "/api/update_board_settings",
    "/api/get_repair_order",
    "/api/update_repair_order",
    "/api/correct_repair_order_number",
    "/api/set_repair_order_status",
    "/api/replace_repair_order_works",
    "/api/replace_repair_order_materials",
    "/api/preview_repair_order_print_documents",
    "/api/export_repair_order_print_pdf",
    "/api/print_repair_order_documents",
    "/api/save_inspection_sheet_form",
    "/api/autofill_inspection_sheet_form",
    "/api/save_print_template",
    "/api/duplicate_print_template",
    "/api/delete_print_template",
    "/api/set_default_print_template",
    "/api/save_print_module_settings",
    "/api/update_card",
    "/api/set_card_board_summary",
    "/api/mark_card_seen",
    "/api/update_sticky",
    "/api/set_card_deadline",
    "/api/set_card_indicator",
    "/api/move_card",
    "/api/mark_card_ready",
    "/api/bulk_move_cards",
    "/api/move_sticky",
    "/api/archive_card",
    "/api/restore_card",
    "/api/delete_sticky",
    "/api/add_card_attachment",
    "/api/remove_card_attachment",
    "/api/upload_shared_file",
    "/api/rename_shared_file",
    "/api/delete_shared_file",
    "/api/paste_shared_file",
    "/api/paste_shared_files_from_clipboard",
    "/api/update_shared_file_position",
}

OPERATOR_SESSION_ROUTES = {
    "/api/logout_operator",
    "/api/get_operator_profile",
    "/api/open_card",
}

ADMIN_ONLY_ROUTES = {
    "/api/list_operator_users",
    "/api/save_operator_user",
    "/api/set_operator_user_employee",
    "/api/delete_operator_user",
    "/api/get_operator_user_report",
    "/api/correct_repair_order_number",
    "/api/finance_audit/apply_safe_fixes",
}


def build_service_routes(
    service: Any,
    shared_files_service: Any,
    *,
    paste_shared_files_from_clipboard: RouteHandler,
) -> dict[str, RouteHandler]:
    def get_repair_order(payload: dict[str, Any] | None) -> dict[str, Any]:
        request_payload = dict(payload or {})
        request_payload.setdefault("create_if_missing", False)
        return service.get_repair_order(request_payload)

    return {
        "/api/create_card": service.create_card,
        "/api/create_column": service.create_column,
        "/api/rename_column": service.rename_column,
        "/api/move_column": service.move_column,
        "/api/delete_column": service.delete_column,
        "/api/create_sticky": service.create_sticky,
        "/api/get_cards": service.get_cards,
        "/api/get_card": service.get_card,
        "/api/get_card_context": service.get_card_context,
        "/api/get_board_revision": service.get_board_revision,
        "/api/get_board_snapshot": service.get_board_snapshot,
        "/api/get_board_context": service.get_board_context,
        "/api/review_board": service.review_board,
        "/api/manager_board_scan": service.manager_board_scan,
        "/api/list_ready_unpaid_cards": service.list_ready_unpaid_cards,
        "/api/triage_inbox_cards": service.triage_inbox_cards,
        "/api/list_cards_missing_manager_data": service.list_cards_missing_manager_data,
        "/api/audit_repair_order_consistency": service.audit_repair_order_consistency,
        "/api/audit_client_links": service.audit_client_links,
        "/api/get_board_content": service.get_board_content,
        "/api/get_board_events": service.get_board_events,
        "/api/list_cashboxes": service.list_cashboxes,
        "/api/get_cash_journal": service.get_cash_journal,
        "/api/finance_audit": service.get_finance_audit,
        "/api/finance_audit/apply_safe_fixes": service.apply_finance_audit_safe_fixes,
        "/api/repair_order_number_audit": service.get_repair_order_number_audit,
        "/api/list_employees": service.list_employees,
        "/api/save_employee": service.save_employee,
        "/api/toggle_employee": service.toggle_employee,
        "/api/delete_employee": service.delete_employee,
        "/api/list_clients": service.list_clients,
        "/api/search_clients": service.search_clients,
        "/api/get_client": service.get_client,
        "/api/get_client_stats": service.get_client_stats,
        "/api/create_client": service.create_client,
        "/api/update_client": service.update_client,
        "/api/delete_client": service.delete_client,
        "/api/link_card_to_client": service.link_card_to_client,
        "/api/unlink_card_from_client": service.unlink_card_from_client,
        "/api/upsert_client_vehicle": service.upsert_client_vehicle,
        "/api/delete_client_vehicle": service.delete_client_vehicle,
        "/api/suggest_clients_for_card": service.suggest_clients_for_card,
        "/api/get_payroll_report": service.get_payroll_report,
        "/api/get_employee_salary_ledger": service.get_employee_salary_ledger,
        "/api/get_employee_salary_report": service.get_employee_salary_report,
        "/api/get_employee_salary_reconciliation": service.get_employee_salary_reconciliation,
        "/api/get_cashbox": service.get_cashbox,
        "/api/create_cashbox": service.create_cashbox,
        "/api/reorder_cashboxes": service.reorder_cashboxes,
        "/api/create_cashbox_transfer": service.create_cashbox_transfer,
        "/api/delete_cashbox": service.delete_cashbox,
        "/api/create_cash_transaction": service.create_cash_transaction,
        "/api/list_inventory_items": service.list_inventory_items,
        "/api/search_inventory_items": service.search_inventory_items,
        "/api/get_inventory_item": service.get_inventory_item,
        "/api/list_inventory_movements": service.list_inventory_movements,
        "/api/save_inventory_item": service.save_inventory_item,
        "/api/replenish_inventory_item": service.replenish_inventory_item,
        "/api/write_off_inventory_item": service.write_off_inventory_item,
        "/api/return_inventory_movement": service.return_inventory_movement,
        "/api/create_employee_salary_transaction": service.create_employee_salary_transaction,
        "/api/create_employee_shift_accrual": service.create_employee_shift_accrual,
        "/api/cancel_cash_transaction": service.cancel_cash_transaction,
        "/api/cancel_last_cash_transaction": service.cancel_last_cash_transaction,
        "/api/get_gpt_wall": service.get_gpt_wall,
        "/api/autofill_repair_order": service.autofill_repair_order,
        "/api/agent_status": service.agent_status,
        "/api/agent_tasks": service.agent_tasks,
        "/api/agent_actions": service.agent_actions,
        "/api/agent_scheduled_tasks": service.agent_scheduled_tasks,
        "/api/agent_enqueue_task": service.agent_enqueue_task,
        "/api/save_agent_scheduled_task": service.save_agent_scheduled_task,
        "/api/delete_agent_scheduled_task": service.delete_agent_scheduled_task,
        "/api/pause_agent_scheduled_task": service.pause_agent_scheduled_task,
        "/api/resume_agent_scheduled_task": service.resume_agent_scheduled_task,
        "/api/run_agent_scheduled_task": service.run_agent_scheduled_task,
        "/api/run_full_card_enrichment": service.run_full_card_enrichment,
        "/api/cleanup_card_content": service.cleanup_card_content,
        "/api/bulk_set_deadline_if_below": service.bulk_set_deadline_if_below,
        "/api/bulk_refresh_board_summaries": service.bulk_refresh_board_summaries,
        "/api/cleanup_card": service.cleanup_card,
        "/api/apply_ready_unpaid_followups": service.apply_ready_unpaid_followups,
        "/api/run_manager_operation": service.run_manager_operation,
        "/api/rollback_manager_run": service.rollback_manager_run,
        "/api/update_board_settings": service.update_board_settings,
        "/api/get_card_log": service.get_card_log,
        "/api/search_cards": service.search_cards,
        "/api/list_repair_orders": service.list_repair_orders,
        "/api/get_repair_order": get_repair_order,
        "/api/update_repair_order": service.update_repair_order,
        "/api/correct_repair_order_number": service.correct_repair_order_number,
        "/api/set_repair_order_status": service.set_repair_order_status,
        "/api/replace_repair_order_works": service.replace_repair_order_works,
        "/api/replace_repair_order_materials": service.replace_repair_order_materials,
        "/api/get_repair_order_text": service.get_repair_order_text,
        "/api/get_repair_order_print_workspace": service.get_repair_order_print_workspace,
        "/api/get_inspection_sheet_form": service.get_inspection_sheet_form,
        "/api/save_inspection_sheet_form": service.save_inspection_sheet_form,
        "/api/autofill_inspection_sheet_form": service.autofill_inspection_sheet_form,
        "/api/preview_repair_order_print_documents": service.preview_repair_order_print_documents,
        "/api/export_repair_order_print_pdf": service.export_repair_order_print_pdf,
        "/api/print_repair_order_documents": service.print_repair_order_documents,
        "/api/save_print_template": service.save_print_template,
        "/api/duplicate_print_template": service.duplicate_print_template,
        "/api/delete_print_template": service.delete_print_template,
        "/api/set_default_print_template": service.set_default_print_template,
        "/api/save_print_module_settings": service.save_print_module_settings,
        "/api/update_card": service.update_card,
        "/api/set_card_board_summary": service.set_card_board_summary,
        "/api/mark_card_seen": service.mark_card_seen,
        "/api/update_sticky": service.update_sticky,
        "/api/set_card_deadline": service.set_card_deadline,
        "/api/set_card_indicator": service.set_card_indicator,
        "/api/move_card": service.move_card,
        "/api/mark_card_ready": service.mark_card_ready,
        "/api/bulk_move_cards": service.bulk_move_cards,
        "/api/move_sticky": service.move_sticky,
        "/api/archive_card": service.archive_card,
        "/api/restore_card": service.restore_card,
        "/api/delete_sticky": service.delete_sticky,
        "/api/list_columns": service.list_columns,
        "/api/list_archived_cards": service.list_archived_cards,
        "/api/list_overdue_cards": service.list_overdue_cards,
        "/api/add_card_attachment": service.add_card_attachment,
        "/api/remove_card_attachment": service.remove_card_attachment,
        "/api/list_card_attachments": service.list_card_attachments,
        "/api/get_card_attachment": service.get_card_attachment,
        "/api/read_card_attachment": service.read_card_attachment,
        "/api/list_shared_files": shared_files_service.list_shared_files,
        "/api/get_shared_file_info": shared_files_service.get_shared_file_info,
        "/api/fetch_shared_file": shared_files_service.fetch_shared_file,
        "/api/upload_shared_file": shared_files_service.upload_shared_file,
        "/api/rename_shared_file": shared_files_service.rename_shared_file,
        "/api/delete_shared_file": shared_files_service.delete_shared_file,
        "/api/copy_shared_file": shared_files_service.copy_shared_file,
        "/api/paste_shared_file": shared_files_service.paste_shared_file,
        "/api/paste_shared_files_from_clipboard": paste_shared_files_from_clipboard,
        "/api/update_shared_file_position": shared_files_service.update_shared_file_position,
    }


def build_operator_routes(operator_service: Any) -> dict[str, RouteHandler]:
    return {
        "/api/login_operator": operator_service.login,
        "/api/logout_operator": operator_service.logout,
        "/api/get_operator_profile": operator_service.get_profile,
        "/api/list_operator_users": operator_service.list_users,
        "/api/save_operator_user": operator_service.save_user,
        "/api/set_operator_user_employee": operator_service.set_user_employee,
        "/api/delete_operator_user": operator_service.delete_user,
        "/api/get_operator_user_report": operator_service.get_user_report,
        "/api/list_operator_activity": operator_service.list_activity,
        "/api/get_operator_activity_details": operator_service.get_activity_details,
        "/api/get_operator_activity_aggregates": operator_service.get_activity_aggregates,
        "/api/export_operator_activity": operator_service.export_activity,
        "/api/open_card": operator_service.open_card,
    }
